name: japanese_voca
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  url_launcher: ^6.1.9
  flutter_svg: ^1.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio: ^4.0.6
  flutter_dotenv: ^5.0.2
  carousel_slider: ^4.2.1
  animate_do: ^3.0.2
  flutter_slidable: ^2.0.0
  flutter_animation_progress_bar: ^2.3.1
  cached_network_image: ^3.2.3
  file_picker: ^5.3.0
  # flutter_tts: ^3.6.3
  google_fonts: ^4.0.4
  excel: ^2.0.4

#  pdfx: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/images/

  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd-Book.ttf

        - asset: assets/fonts/CircularStd-Medium.ttf
          weight: 600

        - asset: assets/fonts/CircularStd-Black.ttf
          weight: 700

        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 900
    - family: ScoreStd
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Caveat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
