import 'package:japanese_voca/model/word.dart';

List<String> hiragas = [
  'あ단',
  'か단',
  'さ단',
  'た단',
  'な단',
  'は단',
  'ま단',
  'や단',
  'い형용사',
  'な형용사',
  '부사',
];

List<Word> temp_words = [
  Word(word: '愛', mean: '사랑', yomikata: 'あい'),
  Word(word: '会う', mean: '사랑', yomikata: 'あう'),
  Word(word: '挨拶', mean: '사랑', yomikata: 'あいさつ'),
  Word(word: '仰ぐ', mean: '우러러보다, 쳐다보다', yomikata: 'あおぐ'),
  Word(word: '商う', mean: '장사하다', yomikata: 'あきなう'),
  Word(word: '値する', mean: '가치가 있다, ~할 만하다', yomikata: 'あたいする'),
  Word(word: '甘える', mean: '응석 부리다, 어리광부리다', yomikata: 'あまえる'),
  Word(word: 'あまりある', mean: '남음이 있다, 하는데 충분하다', yomikata: 'あまりある'),
  Word(word: '改まる', mean: '새로워지다, 격식을 차리다', yomikata: 'あらたまる'),
  Word(word: '案じる', mean: '걱정하다, 염려하다', yomikata: 'あんじる'),
  Word(word: '言い渡す', mean: '알리다, 선고하다', yomikata: 'いいわたす'),
  Word(word: 'いじる', mean: '만지다, 주무르다', yomikata: 'いじる'),
  Word(word: '傷める', mean: '상하게 하다, 망가트리다', yomikata: 'いためる'),
  Word(word: '営む', mean: '경영하다', yomikata: 'いとなむ'),
  Word(word: '愛', mean: '사랑', yomikata: 'あい'),
  Word(word: '会う', mean: '사랑', yomikata: 'あう'),
  Word(word: '挨拶', mean: '사랑', yomikata: 'あいさつ'),
  Word(word: '仰ぐ', mean: '우러러보다, 쳐다보다', yomikata: 'あおぐ'),
  Word(word: '商う', mean: '장사하다', yomikata: 'あきなう'),
  Word(word: '値する', mean: '가치가 있다, ~할 만하다', yomikata: 'あたいする'),
  Word(word: '甘える', mean: '응석 부리다, 어리광부리다', yomikata: 'あまえる'),
  Word(word: 'あまりある', mean: '남음이 있다, 하는데 충분하다', yomikata: 'あまりある'),
  Word(word: '改まる', mean: '새로워지다, 격식을 차리다', yomikata: 'あらたまる'),
  Word(word: '案じる', mean: '걱정하다, 염려하다', yomikata: 'あんじる'),
  Word(word: '言い渡す', mean: '알리다, 선고하다', yomikata: 'いいわたす'),
  Word(word: 'いじる', mean: '만지다, 주무르다', yomikata: 'いじる'),
  Word(word: '傷める', mean: '상하게 하다, 망가트리다', yomikata: 'いためる'),
  Word(word: '営む', mean: '경영하다', yomikata: 'いとなむ'),
  Word(word: '愛', mean: '사랑', yomikata: 'あい'),
  Word(word: '会う', mean: '사랑', yomikata: 'あう'),
  Word(word: '挨拶', mean: '사랑', yomikata: 'あいさつ'),
  Word(word: '仰ぐ', mean: '우러러보다, 쳐다보다', yomikata: 'あおぐ'),
  Word(word: '商う', mean: '장사하다', yomikata: 'あきなう'),
  Word(word: '値する', mean: '가치가 있다, ~할 만하다', yomikata: 'あたいする'),
  Word(word: '甘える', mean: '응석 부리다, 어리광부리다', yomikata: 'あまえる'),
  Word(word: 'あまりある', mean: '남음이 있다, 하는데 충분하다', yomikata: 'あまりある'),
  Word(word: '改まる', mean: '새로워지다, 격식을 차리다', yomikata: 'あらたまる'),
  Word(word: '案じる', mean: '걱정하다, 염려하다', yomikata: 'あんじる'),
  Word(word: '言い渡す', mean: '알리다, 선고하다', yomikata: 'いいわたす'),
  Word(word: 'いじる', mean: '만지다, 주무르다', yomikata: 'いじる'),
  Word(word: '傷める', mean: '상하게 하다, 망가트리다', yomikata: 'いためる'),
  Word(word: '営む', mean: '경영하다', yomikata: 'いとなむ'),
  Word(word: '愛', mean: '사랑', yomikata: 'あい'),
  Word(word: '会う', mean: '사랑', yomikata: 'あう'),
  Word(word: '挨拶', mean: '사랑', yomikata: 'あいさつ'),
  Word(word: '仰ぐ', mean: '우러러보다, 쳐다보다', yomikata: 'あおぐ'),
  Word(word: '商う', mean: '장사하다', yomikata: 'あきなう'),
  Word(word: '値する', mean: '가치가 있다, ~할 만하다', yomikata: 'あたいする'),
  Word(word: '甘える', mean: '응석 부리다, 어리광부리다', yomikata: 'あまえる'),
  Word(word: 'あまりある', mean: '남음이 있다, 하는데 충분하다', yomikata: 'あまりある'),
  Word(word: '改まる', mean: '새로워지다, 격식을 차리다', yomikata: 'あらたまる'),
  Word(word: '案じる', mean: '걱정하다, 염려하다', yomikata: 'あんじる'),
  Word(word: '言い渡す', mean: '알리다, 선고하다', yomikata: 'いいわたす'),
  Word(word: 'いじる', mean: '만지다, 주무르다', yomikata: 'いじる'),
  Word(word: '傷める', mean: '상하게 하다, 망가트리다', yomikata: 'いためる'),
  Word(word: '営む', mean: '경영하다', yomikata: 'いとなむ'),
];
